### ISSUE TITLE
Pilfer

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#1]
Hi NapoleonWilson,
 I see you got the pilfer2 running, Ill give it a shot and see how it is, but i was wondering is there a pilfer for windows x64 still around, I looked in t3rmn8tor's section but couldnt find it. Is the pilfer 2.0 gonna work for windows X64 also? I finally got a better and faster computer.

                                                                                                       Thank You
                                                                                                           Steve

**Comment by NapoleonWils0n** [comment]
hi mate

there is only 32 bit installer by the t3rmin8tor

but you can manually install pilfer 64 bit version
you just need to follow the instructions here

https://github.com/NapoleonWils0n/pilfer

**Comment by NapoleonWils0n** [comment]
hi mate 

i dont think there was a 64 bit installer for rip-record
just 32 bit
