### ISSUE TITLE
Unzipping/extracting

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#10]
Hi NapoleonWilson, Is there a program for ubuntu to unzip folders like power archiver or winzip. My windows crashed or actually for some darn reason i couldnt boot back into windows, so i got ubuntu back on here. Actually i got some folders files back from recovery.

                                                                                                             Thanks
                                                                                                             Steve

**Comment by NapoleonWils0n** [comment]
hi ate

ubuntu comes with a program called archive manager also called file-roller

so you can just double click zio files in the file manager and it should open the program to unzip them

you can also unzip files on the command line as well using unzip
zip and unzip should be installed by default on ubuntu

**Comment by steve55792** [comment]
Thank You, I found the program.

**Comment by NapoleonWils0n** [comment]
hi mate

no problem
