### ISSUE TITLE
reinstalling

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#11]
Hi im trying to reinstall pilfer in ubuntu but i get this message:

mine@mine-OptiPlex-790:~$ sudo apt install -y python3 python3-pip git-core ffmpeg rtmpdump mpv
[sudo] password for mine: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
python3 is already the newest version (3.6.5-3ubuntu1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 cups : Depends: libcups2 (= 2.2.7-1ubuntu2) but 2.2.7-1ubuntu2.1 is to be installed
 cups-bsd : Depends: libcups2 (= 2.2.7-1ubuntu2) but 2.2.7-1ubuntu2.1 is to be installed
            Depends: cups-client (= 2.2.7-1ubuntu2)
 ffmpeg : Depends: libavdevice57 (>= 7:3.4.2) but it is not going to be installed
          Depends: libsdl2-2.0-0 (>= 2.0.8) but it is not going to be installed
 git : Depends: liberror-perl but it is not going to be installed
       Depends: git-man (> 1:2.17.1) but it is not going to be installed
       Depends: git-man (< 1:2.17.1-.) but it is not going to be installed
 mpv : Depends: libavdevice57 (>= 7:3.4.2) but it is not going to be installed
       Depends: libdvdnav4 (>= 4.1.3) but it is not going to be installed
       Depends: libdvdread4 (>= 4.1.3) but it is not going to be installed
       Depends: liblua5.2-0 but it is not going to be installed
       Depends: libsdl2-2.0-0 (>= 2.0.8) but it is not going to be installed
       Depends: libsndio6.1 (>= 1.1.0) but it is not going to be installed
       Depends: libuchardet0 (>= 0.0.1) but it is not going to be installed
       Depends: libva-wayland2 (>= 1.3.0) but it is not going to be installed
       Recommends: youtube-dl (>= 2014.11.26) but it is not going to be installed
 python3-pip : Depends: python3-distutils but it is not going to be installed
               Depends: python-pip-whl (= 9.0.1-2.3~ubuntu1) but it is not going to be installed
               Recommends: build-essential but it is not going to be installed
               Recommends: python3-dev (>= 3.2) but it is not going to be installed
               Recommends: python3-setuptools but it is not going to be installed
               Recommends: python3-wheel but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
mine@mine-OptiPlex-790:~$ 
I never had this happened before.

                                                                                                               Steve

**Comment by NapoleonWils0n** [comment]
hi steve

what a pain

im running ubuntu 18.04 and havent come across that problem

have you tried

sudo apt --fix-broken install

or

sudo apt --fix-broken install 

with the packages you want to install

the other thing i cam across after a quick search was trying

sudo apt update --fix-missing

and then try installing the packages

let me kno wif that helps

**Comment by steve55792** [comment]
Yep, that worked. Thank you again for helping. What caused an issue like that? I never had that problem before.

**Comment by steve55792** [comment]
Yep and thank you NapoleonWilson. Is Tr3mn8tor still around? Havent seen much on windows section.

**Comment by NapoleonWils0n** [comment]
hi mate

termin8tor was away for a couple of months abroad

but hes back now
