### ISSUE TITLE
will it work

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#13]
Hi NapoleonWilson:

the elementary OS 5 'Juno'  came out and they say it would replace windows if a person doesnt like windows 10 anyways, do you think the pilfer/rip-record would work in this OS? And i wonder if Kodi will work in it, I think i read its a mac, sweet if it is i always wanted try or see ow mac  is.

                                                                                                          steve

**Comment by steve55792** [comment]
If i install it will it over write Windows 7 OS or will it be on the side of my windows 7 and Ubuntu, so Ill have 3 operating system on my computer then?  Any how is tr3mn8tor still do his project, seems like he AOL.

**Comment by steve55792** [comment]
Nevermind, ill burn it to a disc  and do it and see what happens.

**Comment by NapoleonWils0n** [comment]
hi mate

id make a backup first

and try it as a live cd

**Comment by steve55792** [comment]
yeah that'll probably  be a good idea.

**Comment by NapoleonWils0n** [comment]
hi steve

if possible back up your bootloader as well as your files

just in case elementary overwrites yiur windows bootloader

**Comment by steve55792** [comment]
ummmmmmm lol, I  gotta readup on that cause i never backup the botloader before. shouldnt be too hard to do.

**Comment by steve55792** [comment]
umm i dont think it gonna work anyways i was using the virtualbox and it said  the kernel requires an x86-64 cpu. and  unable to boot-please use a kernel appropiate for your cpu.

**Comment by NapoleonWils0n** [comment]
hi steve

maybe its 64 bit only

are you on 32 bit
that might be the issue then

**Comment by steve55792** [comment]
Damn, Yep 32 Lol. Oh well. Any News on tr3mn8tor, if he still around and doing his project?

**Comment by steve55792** [comment]
ok cool, i wanna ask him about his pilfer for windows, i installed it the pilfer and nothing  worked. Im gonna unistall it and reinstall and see if it works. When  did he get back, just now  or been back for few  days.
