### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by jcraig999** [NapoleonWils0n/pilfer#17]
Hi,
This isn't really an issue – but I just wanted to say that I really appreciate you making this, and I was wondering if you take donations? Working flawlessly in 2019! :-)

**Comment by NapoleonWils0n** [comment]
hi mate

thats really kind of you

but when i started working all this out and writing the different scripts
i wanted it to free, open source, no ads in youtube, 
pestering people to like me on social media or any donations or any kind of google analytics 

im really glad that pilfer works reliably and you get some use out of it

all goes back to when i first figured out how to save the url from kodi 
and then rearange the url so you could record it

it just nice that my mad little idea still works thats reward enough

 by the way if you are football fan have a look at footybite.com
