### ISSUE TITLE
LinuxMint 19.0 XFCE

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#21]
Hi NapoleonWilson, How you been doing, it been awhile. I was curious if you still mess around with Pilfer with Ubuntu? Because I got my desktop setup with LInux Mint Xfce 19.0(I think its 19.0) but anyways I cant get pilfer setup with Linux Mint XFCE. Can you show me step by step  how to setup Pilfer with Linux Xfce? How in the heck do we get back to kodi 17.6 from 18.5, thats a nother pain in butt IM having. Thank you so much. Ps: I get finished recording 5 secs after i click record.

                                                                                                              Steve

**Comment by NapoleonWils0n** [comment]
hi steve 

good to hear from you mate

it sounds like the version of ffmpeg you have on linux mint is too old
thats why its cutting out after 5 seconds

linux mint is a bit funny with ffmpeg and you need to install ffmpeg via a ppa

this seems to be what most people suggest

open a terminal and run the following commands 

```
sudo apt-get update
sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt-get update
sudo apt-get install ffmpeg
```
from this web page

https://sourcedigit.com/24586-ffmpeg-4-2-ada-install-ffmpeg-4-2-in-ubuntu-18-04/

see if that works for you

i have pilfer working on latest versions of ubuntu, mac catalina ( which is awful ) 
and freebsd

all the best mate

**Comment by steve55792** [comment]
It says I have the latet ffmpeg when i installed it. ffmpeg ver 4.2. I never heard of freebsd for an operating system. Im going to unistall LInux Mint and istall the Ubuntu Latest.

**Comment by NapoleonWils0n** [comment]
hi steve

ubuntu works fine
linux mint has had problems with ffmpeg going back quite a few years 

freebsd is unix 
the sony play station 4 runs on freebsd

glad you got pilfer working on ubuntu
