### ISSUE TITLE
Pilfer

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#22]
Hi NapoleonWilson, how are you today? I was curious, how can I setup pilfer to record audio from Chrome or Firefox because sirrus had a good deal going on right now with 3 months free trial. Not sure if you made a video in youtube about recording pilfer in Chrome/Firefox.

                                                                                                       Thank you
                                                                                                           Steve

**Comment by NapoleonWils0n** [comment]
hi steve

if you press F12 in firefox or chrome it will open the web inspector

if you open the network tab and refresh the page and then play the stream
you shouldthe link to the m3u8 playlist 

then you can copy the m3u8 playlist link and try recording it with pilfer

hope that helps mate
