### ISSUE TITLE
Moving

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#23]
Hi NapoleonWilson:
How have you been with this epidemic crisis we are in? I wondering if there is a way to record to a usb drive instead having the video on desktop when done recording, I know it can copy to a usb drive but i  rather move it to my usb drive. Oh by the way Im on Ubuntu Virtual Machine and I already have my usb drive mounted.
                                                                                                           Steve

**Comment by NapoleonWils0n** [comment]
hi steve 

good to hear from you mate,
uk lockdown is lame especially the supermarket queues, starting to get cabin fever

yes it would be possible to change the recording location

first thing is working out the path to the folder on the usb drive
where is the usb drive mounted

it would easiest to change the script if you could mount the usb drive in your home directory

1 - for example create a mnt directory in your home directory

```
mkdir -p ~/mnt
```

then you need to mount the usb drive to the mnt folder in your home

2- fork the pilfer github repo

you need to have a github account and be logged in and then go to the pilfer page

https://github.com/NapoleonWils0n/pilfer

you should see a button that says fork this repository

click the clone button and it should ley you fork the repository to your github account
so if your username was steve on github the url would look like this

https://github.com/steve/pilfer

3- checkout your git fork of pilfer

create a git/pilfer-fork directory in your home

```
mkdir -p ~/git/pilfer-fork
```

checkout tour version of pilfer
where steve is your guthub username

```
git clone https://github.com/steve/pilfer.git
```

4 - edit your version of pilfer

you would need to edit this file

https://github.com/NapoleonWils0n/pilfer/blob/master/pilfer/record.py

the path when you checkout the git repo would be

pilfer/pilfer/record.py

in the record.py file on line 13 is this code

```
    home = os.path.expanduser('~')
    desktop = 'Desktop'
    time = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    ext = 'mkv'
    recordingfile = os.path.join(home, desktop, 'video-{}.{}'.format(time, ext))
```

this is the recording location
if you have mounted the usb drive to the mnt folder in your home

then you can change recording location from the desktop to the mnt folder

what you would do is change the code so desktop points to the mnt folder instead

desktop = 'mnt'

```
    home = os.path.expanduser('~')
    desktop = 'mnt'
    time = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    ext = 'mkv'
    recordingfile = os.path.join(home, desktop, 'video-{}.{}'.format(time, ext))
```

5 - commit the changes and push to github

commit the changes with a commit message saying usb

```
git commit -m "usb"
```

check the remote git repo name

```
git remote -v
```

if the temote repository is called github
you would run this command or use whatever name the remote git repo is

push the changes to github

```
git push github master
```

6 - unistall my version of pilfer before installing your fork

you need to uninstall my version of pilfer before you install your forked pilfer version

i think the command to unistall with pip should be something like this

```
pip3 uninstall --user git+https://github.com/NapoleonWils0n/pilfer.git
```

7 - install your forked version of pilfer

you can now install your forked version of pilfer
replace steve with your github username

```
pip3 install --user git+https://github.com/steve/pilfer.git
```

if you change the script and push the changes to github and you want to upgrade your installed version of pilfer
then you would run a command like this replacing steve with your github username

```
pip3 install --upgrade --user git+https://github.com/steve/pilfer.git
```

im not a python expert so not sure how to change the code to point to a folder than in your home directory

i know that seems like a lot of steps but at the end of it youll have your own custom version of pilfer

there may be some stuff you need to learn along the way,
but something to do while stuck in doors

hope that helps

**Comment by steve55792** [comment]
Thank you for the information Napoleonwilson,  not much for the lockdown cause i work in the grocery store in the bakery, i would love to have a little vacation soon but not in this pedictiment we are having in this world. LOL. Thank you again and ill give it a shot.
