### ISSUE TITLE
Safe

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#26]
Hi NapoleonWilson, 

Ive been using pilfer  to record videos in the CMD Prompt and it records pretty quick. Just wondering would it be safer to keep on recording in the CMD prompt or start doing in Kodi? (safer I mean with ISP provider and others). I also still use a vpn.
                                                                                                                                               Steve

**Comment by NapoleonWils0n** [comment]
hi steve, good to hear from you mate

it wont make any difference using the cmd prompt or recording from kodi
the connection out to the internet will be the same

recording from kodi is probably easier 
but i like saving the urls and then using the cmd prompt

probably a good idea using a vpn

**Comment by steve55792** [comment]
Thank you NapoleonWilson.

**Comment by steve55792** [comment]
Yeah, I use my real-debrid service to get the links then i use cmd prompt.  I finally figured out that a person can make a bat file of links and click on command prompt to run it(to record one file after another easily.)
