### ISSUE TITLE
Raspi Pi

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#27]
Hi NapoleonWilson, I was wondering if you have any video on using with Raspi Pi, cause I bought one and was curious. Would it be like using Linux?

**Comment by NapoleonWils0n** [comment]
hi steve,
i dont think i have videos about setting up the raspberry pi

you can install linux on the pi
from memory there are installers you can use to set up different linux distros really easily

**Comment by steve55792** [comment]
Oh okay, thank you and I'll give the installer a try. Have a good night NapoleonWilson.

     On Monday, September 21, 2020, 07:46:29 PM CDT, NapoleonWils0n <notifications@github.com> wrote:  
 
 


hi steve,
i dont think i have videos about setting up the raspberry pi

you can install linux on the pi
from memory there are installers you can use to set up different linux distros really easily
