### ISSUE TITLE
avi issue

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#28]

**Comment by steve55792** [comment]
Good Morning/afternoon NapoleonWilson: I was wondering if pilfer had an issue with avi files because when i use it in the command prompt it just stopped, it did leave an .mkv empty file like it didnt record anything.
C:\Users\steve> pilfer -i https://bhs35.download.real-debrid.com/d/OCKH4Z6L3A6AE41/Land%20of%20the%20Lost%20-%202x01%20-%20Tar%20Pit.avi
running ffmpeg command:
frame=    1 fps=0.0 q=-1.0 Lsize=       7kB time=00:00:00.48 bitrate= 123.0kbits/s speed=11.5x
C:\Users\steve>
                                                                                                                                                             Thank you
                                                                                                                                                                Steve

**Comment by NapoleonWils0n** [comment]
hi steve

your right i dont think i set pilfer up to record avi files

not to worry i have a work around
if you paste your avi link in the browser it will download

or you can use wget on the command line

wget 'url goes here'

just run wget then put the url in single quotes and it will download the file

hope that helps mate

**Comment by steve55792** [comment]
oops sorry forgot to mention that i am on windows 10.

**Comment by NapoleonWils0n** [comment]
hi steve

you cam also use ffmpeg to record the avi

```
ffmpeg -i 'url goes here' -c copy outfile.avi
```

**Comment by steve55792** [comment]
Hi NapoleonWilson, 
with the ffmpeg way im getting an invalid argument.

**Comment by steve55792** [comment]
C:\Users\steve>ffmpeg -i 'https://bhs35.download.real-debrid.com/d/OCKH4Z6L3A6AE41/Land%20of%20the%20Lost%20-%202x01%20-%20Tar%20Pit.avi' -c copy Tar Pit.avi
ffmpeg version N-93885-gc61d16cf3b Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 52.101 / 58. 52.101
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 53.101 /  7. 53.101
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
'https://bhs35.download.real-debrid.com/d/OCKH4Z6L3A6AE41/Land%20of%20the%20Lost%20-%202x01%20-%20Tar%20Pit.avi': Invalid argument

**Comment by NapoleonWils0n** [comment]
hi steve

the problem is the output filename

tar pit.avi

ffmpeg thinks you are trying to create 2 files

tar 
pit.avi

try tar-pit.avi

**Comment by steve55792** [comment]
No luck with it, same error from before, weird. Been using a download accelerator plus.
                                                                                                         steve

**Comment by steve55792** [comment]
I probably switch back to Ubuntu, less headaches probably on this kind of things. Which one you prefer for a better connections with the internet cause right now Linux Mint has issues staying connected with my internet, something about the realtek driver finding isuues.

**Comment by NapoleonWils0n** [comment]
hi steve,
i try ubuntu or debian probaly the easiest to set up

**Comment by steve55792** [comment]
Thank you, I'll try Ubuntu.
