### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#29]
Hi NapoleonWilson, how are you doing lately? I'm having a blonde moment here with pilfer, it works fine in kodi when i use it but when i try using it thru the command prompt it give me an error :

C:\Users\steve> pilfer -i https://e202uid.dood.video/u5kj7zzskph3sdgge7gxeyaddpltolkmy5wr3bnfgxf3yw3kw5eeglssthaa/fn5yvhba1x~tx4HU6xpwj?token=y2jwtddjsl5jm3b9gcv6t1o1&expiry=1621186886903|Referer=https%3A%2F%2Fdood.to%2Fe%2Fk0d1rmr8o7vl&User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_4%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F13.1+Safari%2F605.1.15
'pilfer' is not recognized as an internal or external command,
operable program or batch file.
'expiry' is not recognized as an internal or external command,
operable program or batch file.

**Comment by NapoleonWils0n** [comment]
hi steve good to here from you mate
im not too bad

try adding single quotes around the url 

i see in the error message it saying exipry is not recognised as a command
and exipry is in the url so maybe that causing the issue

what happens if you type

```
pilfer -h
```

does that work or give you an error

**Comment by steve55792** [comment]
Same error with pilfer -h

**Comment by NapoleonWils0n** [comment]
hi mate

maybe its an issue with your pilfer not in your windows system path 

https://github.com/NapoleonWils0n/pilfer#add-pilfer-bin-folder-to-windows-system-path


thats the only thing i can think off
maybe an update to windows reset the windows system path

**Comment by steve55792** [comment]
you are probably correct abouy the system path, but if i can record in kodi, isn't it already in the system path?

**Comment by NapoleonWils0n** [comment]
hi steve, you would have thought so

in the playercorefactory.xml i specify the full path to where pilfer is installed
so maybe thats why its working in kodi and not on the command line

only thing i can think of is that its an issue with the windows system path

**Comment by steve55792** [comment]
hmmm, its workin in the command prompt with using .mkv or .mp4 ,  so I'm guessing that's why. Lol, I know it doesn't work with avi. But anyways thank you for helping.
