### ISSUE TITLE
Hi Sir I am the guy from youtube:)

### ISSUE THREAD

**Issue by nostalmia** [NapoleonWils0n/pilfer#31]
Youtube always delete my comments, that's crazy. So I try to contact you here, sorry for the problem.

Thank you so much Sir for your encouragement! Fortunately the difference between the highlight's url- and the full game's url- is so obvious that even Dr. John Watson can detect them:)

The url- of the highlights is very brief. It starts with "mlb-cuts-diamond", and end with m3u8, which seems like a stream format. I have seen m3u8 in some other stream tool like streamlink but not so familiar with them.

The url- of the full game is much longer. Its first small part is a more complex m3u8 link compare to the highlights url-. However, just like Sir your prediction, the residual contains User-Agent parameter and some browser name (Chrome, Safari), followed by a lot random string, and ended with "cookie=".

You are the true Sherlock Holmes:)

[url-2021-08-18-01-42-14.txt](https://github.com/NapoleonWils0n/pilfer/files/7003956/url-2021-08-18-01-42-14.txt)
[url-2021-08-18-01-45-42.txt](https://github.com/NapoleonWils0n/pilfer/files/7003957/url-2021-08-18-01-45-42.txt)

**Comment by NapoleonWils0n** [comment]
Hi Mate, good detective work

the url for the full game has changed since i made the video
thats what the issue is

do you want to give me a email for a chat

t43InvisibleMan@gmail.com

**Comment by nostalmia** [comment]
I have sent a email to you, thank you Sir:)
