### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#35]
Good Morning NapoleonWilson,

How would i setup the at command in a bat file to start at a certain time to run the pilfer commands to record.?

                                                                                                                                             Thank you
                                                                                                                                             Steve

**Comment by NapoleonWils0n** [comment]
hi steve, i dont know anything about bat files on windows im afraid
there is a program on windows called schtasks to schedule commands but i havent got a clue how to use it

im not much of windows expert

**Comment by steve55792** [comment]
Thank you. I probably can talk to tr3mn8tor to see if he knows a few tricks on bat file if he still doing this project of pilfer.
