### ISSUE TITLE
Screen problem

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#40]
Hi NapoleonWilson,

   Good afternoon,  I screwed up on the display settings on ubuntu 22.04, I clicked on  Display for Large Tv(I think thats what it is) and mydisplay screen for Ubuntu is over the extreme unreadable, i barely can read  whats on the top of  screen for ubuntu. Lol, boy did i fucked up. Do you know how to get the display back to normal? even tho i can't get the command prompt on there  either unless there is a  trick to that also when the display poofed out that huge. Im sure glad i left windows 10 alongside Ubuntu 22.04.
                                                                                                                                                              Thank you
                                                                                                                                                                 Steve

**Comment by NapoleonWils0n** [comment]
hi steve, there is supposed to be a file that gets created with those setting

the file is called monitors.xml

it is supposed at this location

```
~/.config/monitors.xml
```

open the terminal and check the file exist by running this command to list the file

```
ls ~/.config/monitors.xml
```

if the file exists try moving it to the desktop

```
mv ~/.config/monitors.xml ~/Desktop
```

then reboot and see if that fixes the issue
hope that helps

**Comment by steve55792** [comment]
Good morning NapoleonWilson,

Thank you for the information and it did work,  not sure what i screwed up on in the first place LOL, I gotta make sure i don't do it again. Like hmmmmm wonder what this will do. Lol

**Comment by NapoleonWils0n** [comment]
HI Steve, no problem mate

what i would recommend is keeping notes with the fixes for things that break
so you if accidentally break it again, you know what the fix is

As Oscar Wilde said "Experience is the name we give to our mistakes"

**Comment by steve55792** [comment]
Good idea, Ya never know if it would happen again or if it would happen to someone else. Its nice to keeps notes. I like the saying from Oscar Wilde.

**Comment by NapoleonWils0n** [comment]
hi steve, its a good idea to have a copy of the notes on another device apart from ubuntu
in case you cant boot into ubuntu to see the notes to fix the problem

you could keep your notes online or a copy on windows as well just to be sure

Oscar Wilde does do good quotes
