### ISSUE TITLE
Ubuntu going to sleep

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#41]
Hi NapoleonWilson, how are you doing? I have a question about Ubuntu 22.0.4.  When i go away from my Ubuntu Computer for like few hours it goes into sleep mode and i have to restart the computer everytime and it doesnt stay on  the job where i left it, like if i have 4 show/movies recording the sleep mode kills the recording and have to restart. Sleep mode if i remember correctly start off where you left it after hitting the spacebar on keyboard. I hope im making sense here.
       
                                                                                                                Thank you

**Comment by NapoleonWils0n** [comment]
HI Steve, had a bit of flu which was lame

If you open the settings on ubuntu and go to the power section,
you can stop the machine going to sleep by setting screen blanking to never

![Screenshot from 2022-12-04 13-54-08](https://user-images.githubusercontent.com/2666091/205494758-7487cb41-64eb-4f02-85c1-2316f19a694f.png)

see if that does the job
