### ISSUE TITLE
KODI 20.1 & Pilfer 2.0 'no such player' 

### ISSUE THREAD

**Issue by FreeBoard976** [NapoleonWils0n/pilfer#44]
Napoleon, - great pilfer code thanks for all the work.  
I installed and cannot get MACos (zsh shell - Ventura) KODI (v20.1) playercorefactory to work - the KODI log advises 'no such player'. 

Pilfer and FFmpeg (N-110094-g20dade27d9-tessus) work in command line (using python 3.11).

I cannot workout why KODI will provide the UI pick list but won't recognize the players, not even the 'save URL' player (see log below) - I have checked the $Path and it seems right.  See below configs (anonymized) and logs.  Any help would be great - as it is driving me nuts!

Terminal
Last login: Tue Mar 28 08:59:56 on console

Machine ~ % echo $PATH
/Library/Frameworks/Python.framework/Versions/3.11/bin:
/Users/username/Library/Python/3.11/bin:
/opt/homebrew/bin:
/opt/homebrew/sbin:
/usr/local/bin:
/System/Cryptexes/App/usr/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/Users/username/bin:
/Users/username/.local/bin

Machine ~ % echo $0
-zsh

Machine ~ % pilfer -i 'https://ABCFile'
running ffmpeg command:
frame=  500 fps=434 q=-1.0 Lsize=    2010kB time=00:00:20.81 bitrate= 791.3kbits/s speed=18.1x  

NANO Edit screen grabs
~/.zshenv 
typeset -U PATH path=(“$HOME/bin” “$HOME/.local/bin” “$path[@]”) export PATH
~/.zshrc
if [-d “$HOME/Library/Python/3.11/bin”]; then PATH=”$HOME/:Library/Python/3.11/bin:$PATH” fi
export PATH
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC -I rc'

KODI 20.1 Log (ex. timestamp):
info <general>: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
info <general>: Loaded playercorefactory configuration
info <general>: Loading player core factory settings from special://profile/playercorefactory.xml.
warning <general>: CPlayerCoreFactory::GetPlayer(save url): no such player: save url
warning <general>: CPlayerCoreFactory::GetPlayer(play): no such player: play
warning <general>: CPlayerCoreFactory::GetPlayer(record video): no such player: record video
warning <general>: CPlayerCoreFactory::GetPlayer(record video - 30 minutes): no such player: record video - 30 minutes
warning <general>: CPlayerCoreFactory::GetPlayer(record video - 1 hour): no such player: record video - 1 hour
warning <general>: CPlayerCoreFactory::GetPlayer(record video - 2 hours): no such player: record video - 2 hours
warning <general>: CPlayerCoreFactory::GetPlayer(record video - 3 hours): no such player: record video - 3 hours
warning <general>: CPlayerCoreFactory::GetPlayer(record audio): no such player: record audio
warning <general>: CPlayerCoreFactory::GetPlayer(record audio - 30 minutes): no such player: record audio - 30 minutes
warning <general>: CPlayerCoreFactory::GetPlayer(record audio - 1 hour): no such player: record audio - 1 hour
warning <general>: CPlayerCoreFactory::GetPlayer(record audio - 2 hours): no such player: record audio - 2 hours
warning <general>: CPlayerCoreFactory::GetPlayer(record audio - 3 hours): no such player: record audio - 3 hours
info <general>: Loaded playercorefactory configuration
info <general>: removing tempfiles
info <general>: initialize done

PlayerCoreFactory XML file

```
<playercorefactory>

<players>
 <player name="save url" type="ExternalPlayer" audio="true" video="true">
	<filename>printf</filename>
     <args>"%s\n" "{0}" > "~/Desktop/url-$(date +"%Y-%m-%d-%H-%M-%S").txt"</args>
     <hidexbmc>false</hidexbmc>
   </player>
   <player name="play" type="ExternalPlayer" audio="false" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilferplay" -i "{0}"</args>
      <hidexbmc>true</hidexbmc>
    </player>
   <player name="record video" type="ExternalPlayer" audio="false" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -i "{0}" &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record video - 30 minutes" type="ExternalPlayer" audio="false" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -i "{0}" -t 00:30:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record video - 1 hour" type="ExternalPlayer" audio="false" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilferr" -i "{0}" -t 01:00:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record video - 2 hours" type="ExternalPlayer" audio="false" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -i "{0}" -t 02:00:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record video - 3 hours" type="ExternalPlayer" audio="false" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -i "{0}" -t 03:00:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record audio" type="ExternalPlayer" audio="true" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -a "{0}" &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record audio - 30 minutes" type="ExternalPlayer" audio="true" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -a "{0}" -t 00:30:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record audio - 1 hour" type="ExternalPlayer" audio="true" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -a "{0}" -t 01:00:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record audio - 2 hours" type="ExternalPlayer" audio="true" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -a "{0}" -t 02:00:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
   <player name="record audio - 3 hours" type="ExternalPlayer" audio="true" video="true">
 	<filename>/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11</filename>
      <args>-E "$HOME/Library/Python/3.11/bin/pilfer" -a "{0}" -t 03:00:00 &</args>
      <hidexbmc>false</hidexbmc>
    </player>
 </players>
 <rules action="overwrite">
   <rule protocols="nfs|smb" player="dvdplayer"></rule>

   <!-- change the default player below -->

   <!-- uncomment to make play the default player
   <rule video="true" player="play"></rule>
    -->

   <!-- uncomment to make record the default player
   <rule video="true" player="record"></rule>
    -->
   
 </rules>
</playercorefactory>
```

**Comment by NapoleonWils0n** [comment]
Hi Mate, sorry your having some bother getting pilfer working on the Mac

You have everything set up properly,
pilfer is working on the command line and your path is correct 
and you have also changed the playercorefactory.xml to the correct location of your python installation

the keyboard shortcut for opening the playercorefactory.xml file changed in kodi 18.6
so you have to press c on a link and then select external player and then the 

[kodi 18.6 keyboard shortcut](https://odysee.com/@NapoleonWils0n:6/kodi-18-6-playercorefactory-xml-fix:8)

I guess you have tried pressing c on the links but i just thought id mention it so we can rule that out as the issue

I havent had anyone else mention any issues with Kodi 20.4 on linux or Windows so it must be a Mac specific issue

kodi is built using python so im wondering if you have to give python full disk access in the mac settings,
system and security tab so that it can find the commands to run from the menu in kodi

the weird thing is that save url which uses printf isnt working as well as the other commands which run python scripts
so the bug isnt specific to trying to run python scripts, the bug affects running any command

it cant be a path issue i wouldnt have thought becuase the playercorefactory.xml has the full path to python and pilfer,
so kodi should be able to find the commands to run

i wondering if its some kind of access control, permission or sandboxing on mac ventura like gatekeeper or sips

some things to try to and narrow down the issue and rule things out

check the file permissions on the playercorefactory.xml file, make sure its not owned by root or something

try giving python full disk access in the mac settings / security tab, and maybe rebooting for good luck

try disabling gatekeeper
https://www.makeuseof.com/how-to-disable-gatekeeper-mac/


i only have an old mac mini which doesnt seem to boot anymore,
so i dont have a mac i can check the bug.

see if any of those suggestions help resolve the issue and let me know how you get on
so we can resolve this issue

Note i had to delete all the Kodi videos from youtube as i kept getting takedown, but all the videos are synced to odysee
[NapoleonWils0n Odysee](https://odysee.com/@NapoleonWils0n:6?)

**Comment by FreeBoard976** [comment]
Yep - I am using the 'c' keyboard shortcut - and it works correctly, the right menu comes up - but any action defaults over to the main player.

Playercorefactory is owned by user with full rights and root only has read access.

I turned off Gatekeeper, Granted full disk access to Python Launcher, and Python IDLE apps (is there another path to an executable that I need to grant FDA to?).

I rebooted - all the same issues.  No luck

Two thoughts:-
has Kodi external player language or rules changed - I see you use 'overwrite' but others seem to have 'prepend'.
Is there another code block to run save url - just as a test to see if it's at the command level or file level?

**Comment by FreeBoard976** [comment]
Napoleon,
Well I am using a xml editor now - emacs.  I checked playercorefactory is in the right place (it is as I can see the log reading it) - I ran it four times with each the code blocks above (I added </players> to close out the code) - & the same log error message each time - no such player.  {with and without Mac restarts}.  

I granted KODI all sorts of application access (disk etc).

Unless you have any other ideas, I have must have a Kodi issue - but I uploaded a new version very recently- is there a version that I should/should not use?.  Is there some sort of clean reinstall I need to do - and how would I clean out any legacy issues?

Thanks again for your assistance, and so sorry this is taking so much of your time...

**Comment by NapoleonWils0n** [comment]
Hi Mate, you have gone through all the posibilites of what could be causing the issue
your right be must be a kodi issue on the mac

you can use AppCleaner to remove Kodi and all its config files
https://freemacsoft.net/appcleaner/

just copy the playercorefactory.xml file to the desktop before you use AppCleaner with Kodi
by default it will delete kodi and all its files but you can deselect files you dont want deleted

all you have to do is open app cleaner and drag kodi into its window
you may have to enter your admin password

the only other version of kodi for the mac is the Development Builds
https://kodi.tv/download/macos

i couldnt find anyone having the same issue doing a quick google,
you could try asking on the kodi forum

https://forum.kodi.tv/

just dont mention you are using pilfer just say external players arent working
i got banned from the kodi forum many years ago

**Comment by NapoleonWils0n** [comment]
HI Mate, i just installed Mac Ventura in a vm and installed Kodi 20.1
when i open kodi it prompted me to allow access in the settings / privacy and security / accessibility

then i copied the playercorefactory.xml file to the ~/Library/Application Support/Kodi/userdata directory
i rebooted kodi pressed c on a link and selected play using and then selected save url and it saved the url to the desktop

so the issue must be with your setup
