### ISSUE TITLE
what happened

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#45]
Good morning / afternoon NapoleonWilson, how have you been? I came up with this error when i tried to record with pilfer:

C:\Users\steve>pilfer -i http://uploaded.net/file/ws80xlks/WCW Fall Brawl.2000.PPV.720p.Web-DL.H264-WWENerd14.mp4 -t 00:30:00
Too many arguments passed to script

-h --help display help
-i 'url' or text file - record video
-a 'url' or text file - record audio
-t '00:00:00'

pilfer -i/-a <url> -t <00:00:00>
What did i do wrong?

                                                                                                                      Thank you 
                                                                                                                        Steve

**Comment by NapoleonWils0n** [comment]
Hi Steve, looking at the command there is a space between WCW Fall
i think that might be the issue

make sure the url is in single quotes

`
pilfer -i 'http://uploaded.net/file/ws80xlks/WCW Fall Brawl.2000.PPV.720p.Web-DL.H264-WWENerd14.mp4' -t 00:30:00
`

see if that works

also the way you install python programs like pilfer has changed on ubuntu 23.04 and debian
you need to use pipx now

[ubuntu pipx pilfer](https://www.youtube.com/watch?v=OFpfcppPHQc)

[pilfer pipx install on ubuntu 23.04](https://github.com/NapoleonWils0n/pilfer#pipx-for-ubuntu-2304-and-debian)

**Comment by steve55792** [comment]
Thank you,  I'll switch over to pipx pilfer.

**Comment by NapoleonWils0n** [comment]
Hi Steve, to uninstall the current version of pilfer installed with pip i think the command should be

`
pip uninstall pilfer
`

then just run these 3 commands to install pilfer with pipx

install pipx

`
sudo apt install pipx
`

ensure path

`
pipx ensurepath
`

pilfer install

`
pipx install git+https://github.com/NapoleonWils0n/pilfer.git
`

**Comment by steve55792** [comment]
Thank you, I'll switch it over

**Comment by steve55792** [comment]
does that include the tsp part also or do we need to put that section into it?

**Comment by steve55792** [comment]
Thank you
