### ISSUE TITLE
Won't record

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#47]
Hi NapoleonWilson, I've gotten everything working with the latest Ubuntu, yahoooooooo. Anyways im on the latest kodi 21 Alpha and  I tried recording  but no luck on saving the video to the desktop, it will save the url to a text. Even when i use thew command prompt with pilfer, no luck on recording anything. Not sure if its Kodi 21 cause thats what ubuntu gave me when i downloaded it to my computer. How would i downgrade to a lower kodi like 18 or 19?

                                                                                                                                       Thank you
                                                                                                                                         Steve

**Comment by NapoleonWils0n** [comment]
Hi Steve, how did you install kodi 21 alpha did you download a .deb file and install it

see if this works

find the name of the package

`
dpkg -l | grep -i kodi
`

which should show you the name of the kodi package

then you can remove kodi like this

`
sudo apt remove kodi
`

**Comment by steve55792** [comment]
That work, thank you,   I wonder if that would fix the issue with it not recording with pilfer if i downgraded to kodi 18 or kodi 19?

**Comment by NapoleonWils0n** [comment]
Hi Steve, you have to use pipx on ubuntu 23.04 to install pilfer
did you use pip and not pipx to install pilfer maybe thats the issue

heres the steps
[pipx-for-ubuntu-2304-and-debian](https://github.com/NapoleonWils0n/pilfer#pipx-for-ubuntu-2304-and-debian)

and a video
[ubuntu 23.04 pipx](https://www.youtube.com/watch?v=OFpfcppPHQc)

if you installed pilfer with pip you can uninstall pilfer like this

`
pip uninstall pilfer
`

**Comment by steve55792** [comment]
Lol, can't remember, which way I did it, but i will unistall pilfer and reinstall it with pipx. Thank you. I have 2 days off of work, so I'll play around.

**Comment by steve55792** [comment]
I got it working now with pilfer, Kodi likes to freeze up on kodi 21. I wanna find a way to downgrade to Kodi 19.
