### ISSUE TITLE
Mpv

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#48]
Hi sir,  I was wondering, in pilfer settings of playercorefactory how can i switch from mpv to vlc for the player cause for some reason when i play a video in kodi it takes forever to load.

                                                                                                                                       Thank you
                                                                                                                                           Steve

**Comment by NapoleonWils0n** [comment]
Hi Steve, if you edit the playercorefacory.xml file and add the following code 
it will create a player called vlc that you can select from the menu

`
   <player name="vlc" type="ExternalPlayer" audio="false" video="true">
		<filename>/usr/bin/vlc</filename>
     <args>"{0}"</args>
     <hidexbmc>true</hidexbmc>
   </player>

`

vlc should be installed to 

`
/usr/bin/vlc
`

you can check where vlc is installed by running

`
which vlc
`

and if vlc is installed somewhere else just change the filepath in the playercorefactory.xml snippet 

see if that works, 
you can also add additional command line arguments to vlc in the playercorefactory.xml file

like setting vlc to be fullscreen

`
   <player name="vlc" type="ExternalPlayer" audio="false" video="true">
		<filename>/usr/bin/vlc</filename>
     <args>"{0}" --fullscreen</args>
     <hidexbmc>true</hidexbmc>
   </player>

`

[vlc command line options](https://wiki.videolan.org/Documentation:Command_line/)

hope that helps

**Comment by steve55792** [comment]
my vlc is in : snap/bin/vlc, I'm guessing every linux os is different.

**Comment by NapoleonWils0n** [comment]
hi steve, try this



<player name="vlc" type="ExternalPlayer" audio="false" video="true">
		<filename>/snap/bin/vlc</filename>
     <args>"{0}" --fullscreen</args>
     <hidexbmc>true</hidexbmc>
</player>

`<player name="vlc" type="ExternalPlayer" audio="false" video="true">
		<filename>/snap/bin/vlc</filename>
     <args>"{0}" --fullscreen</args>
     <hidexbmc>true</hidexbmc>
</player>`

**Comment by steve55792** [comment]
Thank you it works.

**Comment by steve55792** [comment]
switching over to vlc makes it start quicker, for some reason the mpv made it slow. Weird.

**Comment by steve55792** [comment]
Lol, now my kodi freezes and hangs on the startup, anyway to find out what made it hang on startup?
