### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by chrisgatesuk** [NapoleonWils0n/pilfer#5]
Hi mate,

Thanks for all your help and advice so far. You have created an amazing tool. I uninstalled rip-record on my laptop earlier and all associated programs including playercorefactory. Everything seems to be working apart from:

When I try to record using the pilfer GUI using a timestamp, it brings up a CMD window titled C:\.
This window disappears withing 1/2 second and nothing happens. The same thing happens when trying to schedule a recording using the GUI.
When I try to record without a duration it works fine.

As a second problem, I also tried to upgrade this on my desktop computer but this has not worked at all. When I try to record from Kodi it brings up the following windows directory:
C:\Users\Chris
This contains only 1 file: mpv.conf
Nothing else happens.

Any ideas on either problem? Your help would be greatly appreciated as always.

Cheers,

Chris.

**Comment by NapoleonWils0n** [comment]
hi mate

thanks for the feedback

sorry your having a few glitches and its not working on your desktop

i wrote the python scripts that do the recording
but my mate the t3rmin8tor wrote the windows installer and gui

the t3rmin8tor is a windows software engineer and really knows his stuff
and he'll be happy to look into the issue your having and should be able to resolve the issues

could you raise an issue on the windows installer page here

https://github.com/t3rmin8tor/pilfer-installer

you can just copy and paste the issue you raised here into a new issue on the windows installer page
the more info you can provide the easier it will be to get to the root of the issue

could you describe what version of windows you are running and some details about your setup

im not a windows expert, 
but the t3rmin8tor is and if you raise an issue on the windows installer github page he'll get in the case 
and should be able to resolve the issues you are having

cheers mate
