### ISSUE TITLE
Are there known issues with certain URL types?

### ISSUE THREAD

**Issue by sumitdipsite2005** [NapoleonWils0n/pilfer#50]
Hello, I am using pilfer to try to download few streams (all with similar url pattern below) but I only get this in the output and then it exits.
running ffmpeg command:

Url pattern:
http://127.0.0.1:52103/https://d32ubfwfcm754e.cloudfront.net/v1/dash/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/[[redacted_addon_nam]]/index.mpd|User-Agent=Android/Ondemand/609&x-api-client-id=androidphone/2.64.3.609&Authorization=[[redacted_auth_code]]

The stream runs just fine in the kodi addon. I see the auth code changes every time I save the url.
Any ideas how to fix this, if?

**Comment by NapoleonWils0n** [comment]
Hi Mate, i have seen those kind of urls before that start with a localhost address 127.0.0.1
i think they use a local proxy and then connect to the stream

have you tried removing http://127.0.0.1:52103/ from the start of the url
the other issue might be the Authorizatiion= section of the url

pilfer can extract things like cookies, user agent, referer from urls which can be used by ffmpeg
it really depends on the parameters used in the url and if they can be passed to ffmpeg to record the stream

im not sure if the Authorizatiion section refers to cookies or some other kind of authentication
you can use things like the burp suite proxy ot wireshark to look at whats going on

i cant think what else it could be off the top of my head

**Comment by sumitdipsite2005** [comment]
Thanks for the reply Napoleon.
I tried removing the http://127.0.0.1:52103/ from the front but got the
same error.
Wireshark did not help since the site is on https.
I needed to enter a username and password for accessing this stream from
TvNZ+ addon. I think the authorization token is due to that. I am trying to
look up examples on how to use ffmpeg when the site requires a username
password. Have you come across any such examples from your experience?
I will keep looking till I find a solution or till I exhaust all ideas and
give up.





With Regards,
Sumit Sinha

**Comment by sumitdipsite2005** [comment]
I made much headway into solving this.
I am right now at this point.

ffmpeg -allowed_extensions ALL -protocol_whitelist
file,http,https,tcp,tls,crypto,data -header "User-Agent: Mozilla/5.0
(Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/119.0.0.0 Safari/537.36"$'\r\n'"Authorization: Bearer
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFqVkVOalZCTVRORlFUVkVSVEZEUlRJM01UVXlNRVpDTnpjMU4wSkNNamd3T0VORVJURkRNdyJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLnR2bnouY28ubnovIiwic3ViIjoiYXV0aDB8NjU0YjI3OGVlZDYyMzZkYjQ3MWI4ZTgzIiwiYXVkIjpbInR2bnotYXBpcyIsImh0dHBzOi8vdHZuei1wcm9kLmF1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MDEyOTM1MjEsImV4cCI6MTcwMTM3OTkyMSwiYXpwIjoiTG5EQWQ0bUFSY0NnOFZuT2hObXIyMmVsNDZKOTFGbVMiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.M2_trV9JWQBCK7nIuVN9LGCd1jkrW22pC41xb019wXk8acbrYeplSUZHzw5B30lDICJz0HfI8QfUTMPCxgysUg4UcGve9RNY-YDu_lHKAoDEsuMb-kDvdIULdlaBqjU86T3Wmrta0uJE3ch3cRrUtWXRQhJbjI3eF0P8iee4-woxLi53n4NkkgJ3GkrwQ8lF7LONy_XO9I64K8fYWVCrUhU9TtoE3g6k8qtUys-GfqFBBAYBHnYaAsvXo9SqzE7XK4FJSmtWEPAKumqXw08rhNTR04An9AYNtFsX5GbuIBSW0UXkaEnCGNh-ks7MNF40NI79v4cdN7JlZo68SSWvIA"$'\r\n'
-i https://dz1g25geip0uq.cloudfront.net/playlist/playlist.m3u8 -c copy
output.mp4

Resolved many errors and now stuck at some aac audio related errors as
below:
Prediction is not allowed in AAC-LC.
channel element 3.10 is not allocated.
Number of bands (17) exceeds limit (16).

Not sure if you have come access these any may have a ready solution. Lemme
know.



With Regards,
Sumit Sinha

**Comment by sumitdipsite2005** [comment]
Ok, I found the problem.
The streams are DRM protected.

#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,KEYID=0x80723D65B7CA452ECCCB6E9B9F75BD80,URI="data:text/plain;base64,AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8SEMzcqImphEkLtldJjIifl+saBWV6ZHJtSPPGiZsG",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1",IV=0xCCDCA889A984490BB657498C889F97EB

With Regards,
Sumit Sinha

**Comment by sumitdipsite2005** [comment]
Ok, I found the problem.
The streams are DRM protected. Looks like it is a dead end and there may
not be a solution to this!!

#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://ccdca889-a984-490b-b657-498c889f97eb:ccdca889a984490bb657498c889f97eb",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1",IV=0xCCDCA889A984490BB657498C889F97EB

#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,KEYID=0x80723D65B7CA452ECCCB6E9B9F75BD80,URI="data:text/plain;base64,AAAAP3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB8SEMzcqImphEkLtldJjIifl+saBWV6ZHJtSPPGiZsG",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1",IV=0xCCDCA889A984490BB657498C889F97EB

With Regards,
Sumit Sinha

**Comment by sumitdipsite2005** [comment]
Thanks for the tip! So it is not a dead end. It is possible.
There is so much to dig into. I spent all day but still have not gone
through all the links/sub links.
But from what I realize is that getting that license KEY is the main
challenge/bottleneck in the entire process.
And the other concern that I am trying to clear is if it will be possible
to download and watch at the same time a live broadcast (not VOD) using the
process since the decrypting happens after the file has been completely
downloaded. So I would like to download/record and watch at the same time
e.g a live match.
I will spend more time this weekend digging more.
Thanks for the guidance.

With Regards,
Sumit Sinha

**Comment by NapoleonWils0n** [comment]
HI Mate, pilfer doesn't have a log file
