### ISSUE TITLE
mpd (mpeg Dash) streams

### ISSUE THREAD

**Issue by peterpan192** [NapoleonWils0n/pilfer#6]
Hey,
it's me again. Is there a way to record mpd-streams via pilfer or is there any way at all?
I managed to get the '.mpd'-file I need but I didn't have any success from there. 
After having updated to a Kodi-Version that supports inputstream.adaptive, I can play the stream in Kodi but I haven't found a way to record it, yet.

**Comment by NapoleonWils0n** [comment]
hi mate

i havent come across any mpd dash streams in kodi yet

could you post the url and ill have look and try and see what the issue is

**Comment by peterpan192** [comment]
Is there a way to send it to you via pn?

**Comment by NapoleonWils0n** [comment]
hi mate

can send it here

t43invisibleman@gmail.com
