### ISSUE TITLE
Is He still doing the project?

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#7]
Hi NapoleonWilson, 

           I was wondering if tr3mn8tor is still doing the pilfer for windows, cause I haven't seen him on here for while?
                        
                                                                                             thank you           
                                                                                               Steve

**Comment by NapoleonWils0n** [comment]
hi mate

i havent heard from him for few days
so he could be away 

but he'll be back
:)

heres a good article about file sharing

https://medium.com/@ValdikSS/how-to-search-and-download-unpopular-and-old-files-on-the-internet-e5947ef507ba

and heres a video showing you how to download movies and tv shows from irc 

https://www.youtube.com/watch?v=O4o3An-jj9c

i have tried downloading from irc as shown in the video and it does work
and youll find tv show episode and movies that dont show up in kodi using covenant incursion or other scrapers
