### ISSUE TITLE
pilfer

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/pilfer#8]
Hi NapoleonWilson,

I was wondering would pilfer work in linux mint, i didnt see mint but seen other like ubuntu mate and others.

                                                                                                 Steve

**Comment by NapoleonWils0n** [comment]
hi mate

yes it should work on linux mint

i think all the package names should be the same as ubuntu

last time i checked linux mint wasnt as easy to install ffmpeg and some of the other tools
as ubuntu, and i think it may have had older versions of the software

i find debian stable or ubuntu are usually the best to install ffmpeg

**Comment by steve55792** [comment]
Thank You NapoleonWilson, Do you know anything about scraping websites, cause last time I tried scraping in ubuntu i was using python 2.7 to make an xml file but for the life of me I cant find the file in Ubuntu where it is stored  after its done scraping.

**Comment by NapoleonWils0n** [comment]
hi mate

i only know a little about scraping
the requests module is what most people use

http://docs.python-requests.org/en/v2.7.0/

theres a book called python web scraping thats quite good if you can find a copy
